name: Tests and builds app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: npm install

      - run: npm run build

      - name: Git-Pages (ratisbona-coding.org)
        run: |
          docker run --rm \
            -e GIT_PAGES_PASSWORD=${{secrets.GIT_PAGES_KEY_RC_ORG}} \
            -v "${{ github.workspace }}/build:/site" \
            data.forgejo.org/git-pages/git-pages-cli:1.8.2 \
            https://ratisbona-coding.org --upload-dir=/site

      - name: Git-Pages (ratisbona-coding.de)
        run: |
          docker run --rm \
            -e GIT_PAGES_PASSWORD=${{secrets.GIT_PAGES_KEY_RC_DE}} \
            -v "${{ github.workspace }}/build:/site" \
            data.forgejo.org/git-pages/git-pages-cli:1.8.2 \
            https://ratisbona-coding.org --upload-dir=/site